import React, { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { searchService } from '../services/search';
import { usePatient } from '../hooks/usePatient';
import { Input } from '../components/ui/Input';
import { Button } from '../components/ui/Button';
import { Search, Info } from 'lucide-react';
import { EvidenceItem } from '../components/EvidenceItem';

export const AskMedGraphPage: React.FC = () => {
  const { selectedPatientId } = usePatient();
  const [query, setQuery] = useState('');
  const [submittedQuery, setSubmittedQuery] = useState('');

  const { data, isLoading, error } = useQuery({
    queryKey: ['search', selectedPatientId, submittedQuery],
    queryFn: () => searchService.searchRecords(selectedPatientId!, submittedQuery),
    enabled: !!selectedPatientId && !!submittedQuery,
  });

  const handleSearch = (e: React.FormEvent) => {
    e.preventDefault();
    if (query.trim()) {
      setSubmittedQuery(query);
    }
  };

  const suggestions = [
    "What was the HbA1c trend over the last year?",
    "When was Metformin started?",
    "Are there any contraindications in the current medications?",
  ];

  return (
    <div className="max-w-4xl mx-auto space-y-8">
      <div className="text-center py-8">
        <h2 className="text-3xl font-bold tracking-tight text-slate-900 mb-4">Ask MedGraph</h2>
        <p className="text-slate-600 max-w-2xl mx-auto">
          Ask natural language questions about the patient's medical history. Answers are generated by LLM and backed by direct citations to source documents.
        </p>
      </div>

      <form onSubmit={handleSearch} className="relative max-w-2xl mx-auto">
        <Input 
          className="h-14 pl-12 pr-32 text-lg rounded-full shadow-sm"
          placeholder="Ask a question..."
          value={query}
          onChange={(e) => setQuery(e.target.value)}
        />
        <Search className="absolute left-4 top-4 h-6 w-6 text-slate-400" />
        <Button 
          type="submit" 
          className="absolute right-2 top-2 h-10 rounded-full px-6"
          isLoading={isLoading}
        >
          Search
        </Button>
      </form>

      {!submittedQuery && (
        <div className="max-w-2xl mx-auto">
          <p className="text-sm text-slate-500 mb-3 font-medium">Suggestions:</p>
          <div className="flex flex-wrap gap-2">
            {suggestions.map(s => (
              <button 
                key={s}
                onClick={() => { setQuery(s); setSubmittedQuery(s); }}
                className="bg-white border border-slate-200 text-slate-700 px-4 py-2 rounded-full text-sm hover:border-primary-300 hover:text-primary-700 transition-colors"
              >
                {s}
              </button>
            ))}
          </div>
        </div>
      )}

      {data && (
        <div className="bg-white rounded-xl shadow-sm border border-slate-200 overflow-hidden max-w-3xl mx-auto mt-8">
          <div className="bg-primary-50 p-6 border-b border-slate-200">
            <h3 className="font-semibold text-slate-900 mb-2">Answer</h3>
            <p className="text-slate-800 leading-relaxed">{data.answer}</p>
          </div>
          
          <div className="p-6">
            <h3 className="text-sm font-semibold text-slate-900 uppercase tracking-wider mb-4">Citations & Evidence</h3>
            <div className="space-y-4">
              {data.citations.map((cit, idx) => (
                <div key={idx} className="flex gap-4">
                  <div className="shrink-0 w-6 h-6 rounded-full bg-slate-100 flex items-center justify-center text-xs font-medium text-slate-600">
                    {idx + 1}
                  </div>
                  <div className="flex-1">
                    <EvidenceItem 
                      documentId={cit.document_id} 
                      page={cit.page_number} 
                      excerpt={cit.excerpt} 
                    />
                  </div>
                </div>
              ))}
            </div>
          </div>
          
          <div className="bg-amber-50 p-4 border-t border-amber-100 flex items-start gap-3">
            <Info className="w-5 h-5 text-amber-600 shrink-0 mt-0.5" />
            <p className="text-sm text-amber-800">
              <strong>AI-Generated Response:</strong> Always verify information against the source documents before making clinical decisions.
            </p>
          </div>
        </div>
      )}
    </div>
  );
};
